name: Bug report
description: Report a bug or unexpected behavior.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen, and what actually happened?
      placeholder: Clear and concise description.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps or code snippet to reproduce.
      render: python
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste any traceback or torch-audit output.
      render: text
    validations:
      required: false

  - type: input
    id: versions
    attributes:
      label: Versions
      description: torch-audit / torch / python versions (e.g. torch-audit 0.3.0, torch 2.5.1, python 3.11)
      placeholder: "torch-audit 0.3.0, torch 2.x, python 3.x"
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Hardware
      options:
        - CPU
        - CUDA (NVIDIA)
        - MPS (Apple)
        - Other
    validations:
      required: true
